-- CreateTable
CREATE TABLE "Cart" (
    "ID" UUID NOT NULL DEFAULT gen_random_uuid(),
    "quantity" INTEGER NOT NULL,
    "IsArchived" BOOLEAN NOT NULL DEFAULT false,
    "CreatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UserID" UUID NOT NULL,
    "ProductID" UUID NOT NULL,

    CONSTRAINT "Cart_pkey" PRIMARY KEY ("ID")
);

-- AddForeignKey
ALTER TABLE "Cart" ADD CONSTRAINT "Cart_UserID_fkey" FOREIGN KEY ("UserID") REFERENCES "User"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Cart" ADD CONSTRAINT "Cart_ProductID_fkey" FOREIGN KEY ("ProductID") REFERENCES "Product"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;
